version: '3'

services:
  onyconnect:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ony
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
