' Cria o arquivo batch com os comandos
Dim fso, file
Set fso = CreateObject("Scripting.FileSystemObject")
Set file = fso.CreateTextFile("docker_install.bat", True)

file.WriteLine("@echo off")
file.WriteLine("setlocal")
file.WriteLine("")
file.WriteLine(":: Check if Docker is installed")
file.WriteLine("docker --version >nul 2>nul")
file.WriteLine("if %errorlevel% neq 0 (")
file.WriteLine("    echo Docker not found. Installing Docker Desktop...")
file.WriteLine("")
file.WriteLine("    :: Check if Winget is installed")
file.WriteLine("    where winget >nul 2>nul")
file.WriteLine("    if %errorlevel% equ 0 (")
file.WriteLine("        echo Winget found. Installing Docker Desktop with Winget...")
file.WriteLine("        winget install -e --id Docker.DockerDesktop -h")
file.WriteLine("        goto :end")
file.WriteLine("    )")
file.WriteLine("")
file.WriteLine("    :: Check if Chocolatey is installed")
file.WriteLine("    where choco >nul 2>nul")
file.WriteLine("    if %errorlevel% equ 0 (")
file.WriteLine("        echo Chocolatey found. Installing Docker Desktop with Chocolatey...")
file.WriteLine("        choco install docker-desktop -y")
file.WriteLine("        goto :end")
file.WriteLine("    )")
file.WriteLine("")
file.WriteLine("    :: Check if Scoop is installed")
file.WriteLine("    where scoop >nul 2>nul")
file.WriteLine("    if %errorlevel% equ 0 (")
file.WriteLine("        echo Scoop found. Installing Docker Desktop with Scoop...")
file.WriteLine("        scoop install docker")
file.WriteLine("        goto :end")
file.WriteLine("    )")
file.WriteLine("")
file.WriteLine("    :: Install Chocolatey if no package manager was found")
file.WriteLine("    echo No package manager found. Installing Chocolatey...")
file.WriteLine("    powershell -NoProfile -ExecutionPolicy Bypass -Command ""iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))""")
file.WriteLine("    :: Install Docker Desktop with Chocolatey")
file.WriteLine("    choco install docker-desktop -y")
file.WriteLine(")")
file.WriteLine("")
file.WriteLine(":: Try to run Docker Compose")
file.WriteLine("docker-compose up --build -d")
file.WriteLine("if %errorlevel% neq 0 (")
file.WriteLine("    echo An error occurred when running the docker-compose command. Check if Docker is installed correctly.")
file.WriteLine("    echo If the problem persists, download and install Docker manually from the official website: https://www.docker.com/")
file.WriteLine("    goto :end")
file.WriteLine(")")

file.Close

' Executa o arquivo batch criado
Set objShell = CreateObject("WScript.Shell")
objShell.Run "cmd /k docker_install.bat"
