name: Run on Windows

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run
        run: .\windows.cmd